export const FETCHING_PEOPLE = 'FETCHING_PEOPLE';
export const FETCHED_PEOPLE_SUCCESSFUL = 'FETCHED_PEOPLE_SUCCESSFUL';
export const FETCH_PEOPLE_FAILED = 'FETCH_PEOPLE_FAILED';
export const FETCHING_PEOPLE_COUNT = 'FETCHING_PEOPLE_COUNT';
export const FETCHED_PEOPLE_COUNT = 'FETCHED_PEOPLE_COUNT';
export const FETCH_PEOPLE_COUNT_FAILED = 'FETCH_PEOPLE_COUNT_FAILED';
